# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13vKaUNEWWMe1XNbDlDIYtMuC2LLXnGj9
"""

import numpy as np
import matplotlib as plt
import math

C=np.array([[1.6250,-1.9486],[-1.9486, 3.8750]])
mue=np.array([[1],[2]])
W,V=np.linalg.eig(C)
A=np.array([[math.sqrt(W[0])*V[0,0],math.sqrt(W[1])*V[0,1]],[math.sqrt(W[0])*V[1,0],math.sqrt(W[1])*V[1,1]]])
output=[[],[],[],[],[]]

np.random.seed(1472)
for i in range(1,6):
  IN=np.random.randn(10**i,2,1)
  for j in range(10**i):
    output[i-1].append(np.matmul(A,IN[j])+mue)
  output[i-1]=np.array(output[i-1])

def trans(arr):
    x,y=np.shape(arr)
    xarr=np.zeros((y,x))
    for i in range(x):
      for j in range(y):
          xarr[j][i]=arr[i][j]
    return xarr
def MLE(arr):
  mean=trans(np.sum(arr,axis=0)/(np.shape(arr)[0]))
  a=np.zeros((2,2))
  for i in arr:
    a+=(trans(i)-mean)*trans(trans(i)-mean)
  a=a*(1/arr.shape[0])
  K=trans(a)
  return (mean,K)

print('n',end="  |   ")
print('mean',end="  |   ")
print('covariance')
print("---------------------------------------")
for i in range(1,6):
  print(10**i,end="  |   ")
  mean,K=MLE(output[i-1])
  print(mean,end="   |  ")
  print(K)
  print("---------------------------------------")