# -*- coding: utf-8 -*-
"""q4_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGMvxsagd3hJJioXTuwluT07JPIoF-tC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import h5py

x1=h5py.File('../data/mnist.mat','r')
x_imgs=x1.get('digits_train')
x_imgs=np.array(x_imgs,dtype='float32')
x_labels=x1.get('labels_train')
x_labels=np.array(x_labels,dtype='float32')
dig_data=[[],[],[],[],[],[],[],[],[],[]]
for i in range(10):
  dig_data[i]=x_imgs[x_labels[0]==i]
print(dig_data[1].shape)

def mean(arr):
  mean=np.zeros((28,28))
  for i in arr:
    mean=mean+i
  return mean/arr.shape[0]
for i in range(10):
  print('mean of images of digit ',i,':')
  print(mean(np.array(dig_data[i])))
  print('==============================')

