# -*- coding: utf-8 -*-
"""q_1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170lf5GULI0IXvQrEQGJ_8_hHkDdulbZq
"""

import numpy as np
import matplotlib.pyplot as plt

a=4
b=3

np.random.seed(1334)
r_vals=np.random.uniform(0,1,10**7)#generating 10 power 7 unfiromly disti numbers
r_vals=np.sqrt(r_vals)#values of r 
theta_vals=np.random.uniform(0,1,10**7)#theta values
theta_vals=2*np.pi*theta_vals
X=a*r_vals*np.cos(theta_vals)
Y=b*r_vals*np.sin(theta_vals)

plt.xlabel('x->')
plt.ylabel('y')
plt.title('2D histogram of randomly distributed x and y')
plt.hist2d(X,Y,bins=(150,150),cmap=plt.cm.jet)
plt.show()