# -*- coding: utf-8 -*-
"""q_1c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AqFpd2DivZKN_506xoPUchRJkTw8QFPk
"""

import numpy as np
import matplotlib.pyplot as plt

X0=np.random.uniform(0,1,10**7)
y0=np.random.uniform(0,1,10**7)
alpha_set=np.divide(X0,3-2*X0)
beta_set=np.sqrt(y0)
X=np.pi*np.divide(beta_set,2*alpha_set+1)
Y=3*np.e*np.divide(alpha_set*beta_set,2*alpha_set+1)

plt.xlabel('x->')
plt.ylabel('y')
plt.title('hist of randomly generated points inside given traingle')
plt.hist2d(X,Y,bins=(150,150),cmap=plt.cm.jet)
plt.show()